# Generated by Django 4.2.5 on 2023-09-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_rename_pic_profile_cover_pic_pro_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='status',
            new_name='title',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
