# Generated by Django 4.2.5 on 2023-09-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_rename_status_profile_title_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='describtion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
