# Generated by Django 4.2.5 on 2023-09-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_profile_adress_profile_describtion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='describtion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
