# Generated by Django 4.2.5 on 2023-09-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_alter_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pro_pic',
            field=models.ImageField(blank=True, null=True, upload_to='pro_pic'),
        ),
        migrations.DeleteModel(
            name='Pro_pic',
        ),
    ]
