# Generated by Django 4.2.5 on 2023-09-19 10:42

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_profile_pro_pic_delete_pro_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_user',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=25)),
                ('caption', models.TextField()),
                ('post_img', models.ImageField(upload_to='post_user')),
                ('likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
