# Generated by Django 4.2.5 on 2023-09-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_alter_profile_cover_pic_alter_profile_pro_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_pic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='pic'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pro_pic',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='pro_pic'),
        ),
    ]
